spring:
  datasource:
    url: jdbc:mysql://localhost:3307/sfw_dev
    username: sfw_dev_user
    password: my_secret_pw
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true